### PR TITLE
Fix pcontains

### LINKED ISSUE #705: Bug in `pcontains`
It appears that `pcontains` is not working properly.

```hs
ghci> i1
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 120})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 129})) False}
ghci> i2
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 120})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 129})) True}
ghci> contains i2 i1
True
ghci> plift $ pcontains # pconstant i2 # pconstant i1
False
```

As far as I can tell, it works when the upper bound for both are closed, but not when one is open. We should have the $[120, 129) \subseteq [120, 129]$, but we don't.

### PR DESCRIPTION
**Pull request by kozross**
This fixes #705, by making use of the `PEnumerable` machinery provided earlier. Also includes a test to ensure this bug remains fixed later.

### CODE REVIEW

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs [hunk 1]
```diff
@@ -273,10 +296,112 @@ pmember ::
...
+    )
+  where
+    go ::
+      forall (s' :: S).
+      Term s' (PInterval a) ->
+      Term s' (PInterval a) ->
+      Term s' PBool
+    go i1 i2 = unTermCont $ do
+      unpackedI1 <- tcont $ pletFields @'["from", "to"] i1
+      unpackedI2 <- tcont $ pletFields @'["from", "to"] i2
```
Comment (SeungheonOh) [inline plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:397]: This unpacking computation is duplicated. `pisEmpty` unpacks values and this part does it again from scratch, unpacking same thing twice.

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs [hunk 2]
```diff
@@ -176,16 +191,24 @@ newtype PUpperBound (a :: S -> Type) (s :: S)
...
     , -- | @since 2.0.0
       POrd
     , -- | @since 2.0.0
       PShow
     )
 
+-- | @since WIP
+instance (PIsData a, PEnumerable a) => PEq (PUpperBound a) where
+  {-# INLINEABLE (#==) #-}
+  ub1 #== ub2 = (pinclusiveUpperBound # ub1) #== (pinclusiveUpperBound # ub2)
```
Comment (SeungheonOh) [inline plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:203]: Do we want this as default comparison? instead of Eq checking if two bounds are strictly equal (by definition)?

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs [hunk 3]
```diff
@@ -273,10 +296,112 @@ pmember ::
...
+
+@since WIP
+-}
+pinclusiveLowerBound ::
+  forall (a :: S -> Type) (s :: S).
+  (PIsData a, PCountable a) =>
+  Term s (PLowerBound a :--> PExtended a)
+pinclusiveLowerBound = phoistAcyclic $ plam $ \lb -> unTermCont $ do
+  unpacked <- tcont $ pletFields @'["_0", "_1"] lb
+  let extended = getField @"_0" unpacked
```
Comment (SeungheonOh) [inline plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:325]: as `extended` is used twice, once each on `pif` this should technically use `plet` but I think it's fine here

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs (hunk 2 above)
Comment (kozross) [reply plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:203]: This is identical to how they're checked by Plutus. Doing it the way you suggest would make it inconsistent with the order semantics.

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs (hunk 3 above)
Comment (kozross) [reply plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:325]: Easy to change.

File: plutarch-ledger-api/test/Regressions.hs [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+  UpperBound (UpperBound),
+ )
+import PlutusLedgerApi.V1.Interval qualified as Interval
+import PlutusLedgerApi.V1.Time (POSIXTime)
+import Test.Tasty (TestTree)
+import Test.Tasty.HUnit (assertEqual, testCase)
+
+tests :: [TestTree]
+tests =
+  [ testCase "705" $ do
```
[the remark this answers is not in the document]
Comment (kozross) [reply plutarch-ledger-api/test/Regressions.hs:19]: Yes, you're correct. I'll fix this.

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs (hunk 2 above)
Comment (SeungheonOh) [reply plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:203]: > This is identical to how they're checked by Plutus
Okay. Let's stick to this

File: plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs (hunk 3 above)
Comment (kozross) [reply plutarch-ledger-api/src/Plutarch/LedgerApi/Interval.hs:325]: On second look, this isn't the best idea:

`  ./Plutarch/Test/Golden.hs:256:3: 
  2) Plutarch.Extra.Interval.extra.intervalutils.fixtures.golden bench
       expected: constants.always {"exBudgetCPU":16100,"exBudgetMemory":200,"scriptSizeBytes":34}
                 contains.in interval {"exBudgetCPU":28461443,"exBudgetMemory":97463,"scriptSizeBytes":553}
                 contains.out interval {"exBudgetCPU":22778323,"exBudgetMemory":79756,"scriptSizeBytes":552}
                 contains.always {"exBudgetCPU":22193602,"exBudgetMemory":75658,"scriptSizeBytes":561}
                 member.[b,c], a < b {"exBudgetCPU":22459810,"exBudgetMemory":78292,"scriptSizeBytes":562}
                 member.[b,c], a = b {"exBudgetCPU":28094930,"exBudgetMemory":95699,"scriptSizeBytes":556}
                 member.[b,c], a > b, a < c {"exBudgetCPU":28142930,"exBudgetMemory":95999,"scriptSizeBytes":562}
                 member.[b,c], a = c {"exBudgetCPU":28142930,"exBudgetMemory":95999,"scriptSizeBytes":559}
                 member.[b,c], a > c {"exBudgetCPU":28142930,"exBudgetMemory":95999,"scriptSizeBytes":562}
                 hull.hull 3 5 contains 3 5 {"exBudgetCPU":45167369,"exBudgetMemory":156699,"scriptSizeBytes":999}
                 hull.2 not member of hull 3 5 {"exBudgetCPU":39309736,"exBudgetMemory":138428,"scriptSizeBytes":982}
                 hull.6 not member of hull 3 5 {"exBudgetCPU":39309736,"exBudgetMemory":138428,"scriptSizeBytes":982}
                 intersection.intesection [2,4] [3,5] contains [3,4] {"exBudgetCPU":45708395,"exBudgetMemory":159027,"scriptSizeBytes":999}
                 intersection.intesection [3,5] [2,4] contains [3,4] {"exBudgetCPU":51016829,"exBudgetMemory":177081,"scriptSizeBytes":999}
        but got: constants.always {"exBudgetCPU":16100,"exBudgetMemory":200,"scriptSizeBytes":34}
                 contains.in interval {"exBudgetCPU":28653443,"exBudgetMemory":98663,"scriptSizeBytes":552}
                 contains.out interval {"exBudgetCPU":22970323,"exBudgetMemory":80956,"scriptSizeBytes":551}
                 contains.always {"exBudgetCPU":22385602,"exBudgetMemory":76858,"scriptSizeBytes":560}
                 member.[b,c], a < b {"exBudgetCPU":22651810,"exBudgetMemory":79492,"scriptSizeBytes":561}
                 member.[b,c], a = b {"exBudgetCPU":28286930,"exBudgetMemory":96899,"scriptSizeBytes":555}
                 member.[b,c], a > b, a < c {"exBudgetCPU":28334930,"exBudgetMemory":97199,"scriptSizeBytes":561}
                 member.[b,c], a = c {"exBudgetCPU":28334930,"exBudgetMemory":97199,"scriptSizeBytes":557}
                 member.[b,c], a > c {"exBudgetCPU":28334930,"exBudgetMemory":97199,"scriptSizeBytes":561}
                 hull.hull 3 5 contains 3 5 {"exBudgetCPU":45359369,"exBudgetMemory":157899,"scriptSizeBytes":998}
                 hull.2 not member of hull 3 5 {"exBudgetCPU":39501736,"exBudgetMemory":139628,"scriptSizeBytes":980}
                 hull.6 not member of hull 3 5 {"exBudgetCPU":39501736,"exBudgetMemory":139628,"scriptSizeBytes":980}
                 intersection.intesection [2,4] [3,5] contains [3,4] {"exBudgetCPU":45900395,"exBudgetMemory":160227,"scriptSizeBytes":997}
                 intersection.intesection [3,5] [2,4] contains [3,4] {"exBudgetCPU":51208829,"exBudgetMemory":178281,"scriptSizeBytes":998}
`

Gonna leave it as-is.

**Review by SeungheonOh — APPROVED** [review]
Thanks!
